---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  fig.path = "man/figures/README-"
)
```

# pmtables

<!-- badges: start -->
<!-- badges: end -->

Tables for pharmacometrics

## Installation

Installation information to be updated when ready.


## Examples

Continuous covariate summary!

```{r, message = FALSE, warning = FALSE}
library(dplyr)
library(pmtables)


data <- pmtables:::data("id") 
data <- mutate(data, STUDY = STUDYf)
```

# Continuous by study
```{r}
pt_cont_study(
  data, 
  cols = vars(BMI,ALB,AAG), 
  study_col = vars(Study = STUDY)
) 
```



# Categorical by study
```{r}
pt_cat_study(
  data, 
  cols = vars(Sex = SEXf,"Renal function" = RFf), 
  study_col = vars(Study = STUDY)
) 
```

## Wide version
```{r}
pt_cat_study(
  data, 
  cols = vars(Sex = SEXf,"Renal function" = RFf), 
  study_col = vars(Study = STUDY), 
  wide = TRUE
) 
```


# Data disposition


```{r,eval=FALSE}
data <- pmtables:::data("id")
pt_data_inventory(
  data, 
  outer = "STUDYf"
)
```

