name: Deploy site
on:
  push:
    branches:
      - scratch/deploy-site
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch tags for more informative git-describe output.
          fetch-depth: 0
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # The latest pkgdown release (v2.1.1) is not compatible with the
          # generated favicons.  Install from GitHub to get fix in dd777ee8.
          # This can be changed to any::pkgdown after that fix is released.
          extra-packages: r-lib/pkgdown
      - name: Build site
        run: pkgdown::build_site_github_pages(dest_dir = "docs", install = TRUE)
        shell: Rscript {0}
      - uses: metrumresearchgroup/actions/subdir-to-gh-pages@v1
